### PR TITLE
correcting some problems to handle ghost atoms

### PR DESCRIPTION
**Pull request by mbarbry**
Hello Peter,

I tried to run an example with a silver cluster with ghost atoms. I faced some problems that I tried to correct.

I added also a data folders containing informations on atoms that may be useful (I took it from the ase code).

Best regards,
marc

### CODE REVIEW

**Comment by kovalp** [comment]
Ok, I see you already merged these corrections.

Peter

**Comment by mbarbry** [comment]
Sorry, I thought I did a merge request, I probably mistook of button. 
Hope that the corrections are ok for you?

marc

**Comment by kovalp** [comment]
I think they are ok. We discussed these changes over and agreed, but we
need some testing facility.

**Comment by mbarbry** [comment]
The Ag13 + ghost could be use for testing here, or you prefer a test 
with more chemical element?

marc

**Comment by kovalp** [comment]
I meant a general automated testing we need.

**Comment by mbarbry** [comment]
In ASE they have a really good method for testing, I will look around to 
see how they do and we can try to use the same method.

**Pull request merged**
