### PR TITLE
starting prod_basis class

### PR DESCRIPTION
**Pull request by mbarbry**
Hello Peter,

I started to look for the prod basis initialization (for the moment only the inputs initialization).
Do you agree with this dictionary structure for input parameters?

I think the advantage of this structure is that it is easy to change the value by using another dictionary as input.

### CODE REVIEW

**Comment by kovalp** [comment]
Dear Marc,

I am not sure we will need such data as any entries in any dictionary. We
were forced to do this in fortran because we needed some input stored. This
will be more elegant with python I hope...

Peter

**Comment by kovalp** [comment]
I think this

  def sp2ion_to_j_rcut(self):
    """ Extract mu_sp2j and self.mu_sp2rcut for each specie """
    nspecies = len(self.sp2ion)
    if nspecies <1: return

    nmu_mx = max(self.sp2ion[sp]["paos"]["npaos"] for sp in range(nspecies))
    self.mu_sp2j = np.zeros((nmu_mx, nspecies), dtype='int64')
    self.mu_sp2rcut = np.zeros((nmu_mx, nspecies), dtype='float64')

    for sp, ion in enumerate(self.sp2ion):
      npaos = ion["paos"]["npaos"]
      self.mu_sp2rcut[0:npaos, sp] = ion["paos"]["cutoff"]
      for pao, orb in enumerate(ion["paos"]["orbital"]):
        self.mu_sp2j[pao, sp] = orb["l"]

is a better solution than I found (in m_siesta_ion_add_sp2.py)

Could you rename it however to "_add_mu_sp2" (with underscore to show that
it is manipulating with the class).

I also think that this function can be useful in ao_log class for instance.
So, it is useful to have it as function adding fields to given object...

Best regards,

Peter

**Comment by mbarbry** [comment]
I will do the corrections.

Otherwise how are you thinking to handle the input parameters?

**Comment by kovalp** [comment]
we don't need input parameters. They will be specified in the main script...

**Comment by mbarbry** [comment]
yes, I find also nicer to specify input from the main script than from an external file (more phytonic).
But the input are still there (that they are from an external file or directly specified in the main script) and I believe that dictionaries are good tools to handle this kind of issues, no?

**Pull request merged**
