### PR TITLE
better cmake for debug

### PR DESCRIPTION
**Pull request by mbarbry**
Hello Peter,

I corrected the CMake files in order that it uses correctly debug flags or not.
If you want to compile with debug flags, you should specifie in the setup.py file build_type="Debug".

Otherwise, for using the optimal flag you should use build_type="Release"

### CODE REVIEW

**Comment by kovalp** [comment]
it doe not work for me. It always generating debug version

**Comment by mbarbry** [comment]
in the setup.py file, you should replace Debug by Release in line 69

**Comment by kovalp** [comment]
This is an as bad solution as previously! This is so because I need to
change the distributed file (setup.py now, CMakeLists.txt previously) to
achieve the effect I wanted only temporarily, on my machine, at one
particular time.

**Comment by mbarbry** [comment]
It is true that we still need to change a file but I find it cleaner like this and all the generated code is now with debug flags (not only the fortran one). Also, I don't know you, but I had before a mess in my flags like -O0 -g -O2 -g .... while now it is more consistent.

**Pull request merged**
