### PR TITLE
openmp m_ao_eval + modification param install

### PR DESCRIPTION
**Pull request by mbarbry**
Hello Peter,

small improvements of ao_eval subroutine by adding openmp.I also changed the default parameters in the install routine.

### CODE REVIEW

**Comment by kovalp** [comment]
OpenMP is realized wrongly because arrays lm2aa, lm2bb, l2tlp1, l2tlm1,
l21mhl and integer lmx should be shared. They are used to store some
constants and are not modified during calculation of spherical harmonics.
The implementation might work, but it duplicates data.

**Comment by mbarbry** [comment]
Ok, I misunderstood the routines so. I will correct this.

**Comment by mbarbry** [comment]
I corrected the issue with the duplicates data. I added also some comments in m_coulomb_am because I think it is a routine that we can improve the efficiency. I tried a bit with fortran, but it revealed to be more complicate than what I was thinking (mainly the c2r transformation is causing me troubles at the moment). An easier solution could be the use of numba library. What do you think?

**Comment by kovalp** [comment]
CMake Error at nao/CMakeLists.txt:3 (add_library):
  Cannot find source file:

    m_coulomb_am.F90

Forgot to add the file ?

**Comment by kovalp** [comment]
Do you know why the compiler flags set in the root CMakeLists.txt file

if (CMAKE_COMPILER_IS_GNUCC) # Does it skip the link flag on old OsX?

  message ("setting or not ????  ${CMAKE_COMPILER_IS_GNUCC}")

  set(CMAKE_C_FLAGS_DEBUG "-Wall -pg -O0")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ")
  set(CMAKE_C_FLAGS_RELEASE "-Wall -O2 -ffast-math")
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ")
  set(CMAKE_FORTRAN_FLAGS_DEBUG "-pedantic -pg -DDEBUG -O0 -fbounds-check
-fbacktrace -Wall -ffree-line-length-0")
  set(CMAKE_FORTRAN_FLAGS_RELEASE "-pedantic -O2 -Wall
-ffree-line-length-0")
  if(UNIX AND NOT APPLE)
    set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--no-as-needed")
  endif()
endif()


are not effective when doing a manual installation without install.py ?

Peter

**Comment by kovalp** [comment]
Even with after compiled library, the new version does not verify test!

**Comment by mbarbry** [comment]
This is weird, I will look.

**Comment by kovalp** [comment]
FAILED (failures=1)
kovalp@kovalp-ThinkPad-T460 ~/programs/pyscf $ python
test/test_0011_ao_eval.py
F
======================================================================
FAIL: test_ao_eval (__main__.KnowValues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_0011_ao_eval.py", line 26, in test_ao_eval
    self.assertAlmostEqual(ao_vals_lib[0,0], 0.021725938009701302)
AssertionError: 0.0 != 0.021725938009701302 within 7 places

----------------------------------------------------------------------
Ran 1 test in 0.132s

FAILED (failures=1)

**Comment by kovalp** [comment]
There was also a segfault when doing all tests at once.

**Comment by mbarbry** [comment]
The problem with CMake is that you need now to specify the build type while doing cmake, there is no default Flags otherwise, I will correct this.

**Pull request merged**
