### PR TITLE
numba to calculate bessel functions

### PR DESCRIPTION
**Pull request by mbarbry**
using numba allows to get a speed up of 70 s on my computer (~15% speed up).

### CODE REVIEW

**Comment by kovalp** [comment]
Hello Marc,

I think there are several possible ways to improve the code. Probable the
best for now would be a program which computes the blocks of Hartree kernel
for a given list of atom pairs on the fortran side and a python interface
which uses this program to compute (gather) the dense matrix kernel.

The generation of bilocal products is also improvable, but let me do this
when I am back from vacations. The version which works now (batch) must be
even faster than we have in mbpt_lcao.

Computation of xc kernel is probable improvable, but I would like to do
this for a spin-resolved case first, before any optimization is tackled.

Probable when we have a decent speed because of using the list-of-blocks
interface for kernels, you could think about mpi parallelization and I will
write up a paper presenting this code. For this we could use relatively
modest calculations as C60, Ag561, and Na380 dimer. Furthermore, we will
need to present at least minimal examples of interfacing with other dft
codes such as pyscf itself, gpaw, maybe fireball and adf.

Further work, I would like to do about gw (spin resolved) and bse solver.
For this, i will need the Fock operator to be implemented.

Best regards,

Peter




28 Июл 2017 г. 13:20 пользователь "mbarbry" <notifications@github.com>
написал:

**Comment by kovalp** [comment]
15% speedup to the total time or to the computation of the kernel?

28 Июл 2017 г. 13:20 пользователь "mbarbry" <notifications@github.com>
написал:

**Comment by mbarbry** [comment]
Hello Peter,

it is 15% speed-up to the total time. For the Hartree kernel the speed-up is 460%.

I will try to write Fortran version of the Hartree kernel then, it will probably be make more sens than only numba, particularly for large systems.

Best regards,
marc

**Comment by kovalp** [comment]
Cool. 4x speedup in the hartree kernel is very nice. Fortran version could
be only little faster. Maybe computation of spherical bessel functions with
numpy will be more universal.

Peter

**Pull request merged**
