### PR TITLE
avoiding null delta for dmin

### PR DESCRIPTION
**Pull request by mbarbry**
In order to avoid null value for dmin (that would caused undefine value for kmax), one need to do a bit more steps. I got null value for delta in the case of silver ghost atom.

I added a few comment as well (I think we should really take the chance the document well the code).

### CODE REVIEW

**Comment by kovalp** [comment]
Hm... can we just ensure that deltas are defined in the ion dictionary? I
would only assert this in the ao_log...

You tell ion structure, but this is indeed a dictionary
..Peter

**Comment by mbarbry** [comment]
Yes it is true that ion is a dictionary, not a structure.

Concerning the value of delta, I don't know how to ensure that the 
values are define, maybe while reading the dictionary.
If the delta is 0.0, then take the previous value, what do you think?

marc

**Comment by kovalp** [comment]
I think there must be a more robust way to define these records, let's see
tomorrow.

Peter

**Comment by kovalp** [comment]
There were nice terse one-liners for each of the parameters and you added dozens of lines of code :-( The fields must be in the dictionary in order the initialization functions. If the fields are not defined, then the exception is raised and the program stops. We should not do anything more... Maybe the ghost species files from the .ion.xml files are not existing or not properly recognized in the ion.xml reader? I like the documentation, but I don't like the rest, sorry.

**Comment by kovalp** [comment]
I remember I started a .ion file reader directly in python...

**Comment by kovalp** [comment]
Can you add an example generating the .ion.xml files with ghost atoms?

Peter

**Comment by mbarbry** [comment]
I agree that the code become more complex, but I din't find anything 
else for the moment.
The problem is not coming from the reader, it is just reading the value 
from the xml file, the zero are there (see attached file, line 1590). I 
will try to do something else, directly in the reader, I guess if the 
value is null there is no point reading it at all, and then avoiding the 
zeros.

marc

**Comment by mbarbry** [comment]
I added the following keys to the ion dictionary,
'paos', 'kbs', 'vna', 'chlocal', 'reduced_vlocal', 'core'
I hope to not have forgot any.

In the code I assumed that you need only the one coming from paos, is it correct?

**Comment by kovalp** [comment]
I guess this must be fine. I only use paos...

**Pull request merged**
