### PR TITLE
checking overlap between pyscf and gpaw

### PR DESCRIPTION
**Pull request by mbarbry**

### CODE REVIEW

**Comment by kovalp** [comment]
could you not touch m_comp_overlap_coo and m_ao_log_hartree ? I believe
this was pointless this time.

**Comment by mbarbry** [comment]
yes, I just copied back from the github repo the routines that I modified, but there is maybe small changes in the format. Nevertheless, the routines should be the same as before.

**Comment by mbarbry** [comment]
So I guess that the next step is to extract the Hamiltonien from gpaw?
Should we create a gpaw_hsx_c class?

**Comment by kovalp** [comment]
yes. This is the next step along this line. And put the computed overlap in
gpaw_hsx. In wfsx there should be no overlap.

**Comment by kovalp** [comment]
Sorry. For tddft we do not use the Hamiltonian... Therefore, it is not
strictly necessary for starting tddft_iter.

We may skip the getting of Hamiltonian.

Peter

**Comment by kovalp** [comment]
Actually, if we have all states, we may reconstruct hamiltonian from them...

**Comment by mbarbry** [comment]
ok, this is good, I don't to bother to retrieve the Hamiltonian from the gpaw code (at least for the moment). I will try to run tddft with gpaw input.

**Comment by kovalp** [comment]
You may still move the overlap to hsx from wfsx and store the overlap in
the csr format there.

**Pull request merged**
