### PR TITLE
pyscf compile with intel; need some correction in lib/nao/m_system_va…

### PR DESCRIPTION
**Pull request by mbarbry**
Hello Peter,

I modified the CMake to include the intel compiler. It was necessary to do some changes in m_system_vars.F90 I wrote some comments in the file about it.

marc

### CODE REVIEW

**Comment by kovalp** [comment]
Ok. Cannot we consistently use the function allocated()?

**Comment by mbarbry** [comment]
What about we store the size of the array into a variable? I find it more clean than allocating an array that is not gonna to be use.

**Comment by kovalp** [comment]
Just deallocate the eigenvectors. Then, use function to get the pointer to
eigenvectors if they are deallocated the function will die(...).

Maybe there is an excessive checking on number of orbitals? This can be
corrected.

Indeed, we are not using the eigenvectors on fortran site, at least now.

Peter

**Comment by kovalp** [comment]
I think there should be a more standard way of specifying the compiler
version rather than using a homemade option. For intance, the environment
variables FC, CC could be used.

Also introducing if cases to the CMakeLists seems to be a Neolithic
solution (deMon is using bash scripts for compilation and there are a lot
of cases, Fireball is using Makefiles and also some cases). Doesn't it work
via include files?

Peter

**Comment by mbarbry** [comment]
There is probably much better way to do this I agree with you. My knowledge of CMake is very limited. I will try to look up some CMake tutorial during the holiday. Inigo probably know well CMake
, I will ask him

**Comment by mbarbry** [comment]
Hello Peter,

I included a variable to transfer the size of the wavefunction array from python to fortran to avoid to allocate it on the Fortran side while it is not gonna to be use. What do you think?

I will try to improve the cmake to include correctly intel compiler.

I hope that I do not bother you during your holidays, if you prefer I can do some changes in this branch and we can talk about them once you are back in Donostia.

Good holidays,
marc

**Comment by kovalp** [comment]
Hi. I think it is ok. Later we will discuss more detailed.

Peter

El 2 ago. 2017 15:09, "mbarbry" <notifications@github.com> escribió:

Hello Peter,

I included a variable to transfer the size of the wavefunction array from
python to fortran to avoid to allocate it on the Fortran side while it is
not gonna to be use. What do you think?

I will try to improve the cmake to include correctly intel compiler.

I hope that I do not bother you during your holidays, if you prefer I can
do some changes in this branch and we can talk about them once you are back
in Donostia.

Good holidays,
marc

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kovalp/pyscf/pull/28#issuecomment-319653425>, or mute
the thread

**Comment by mbarbry** [comment]
Hello Peter,

Following the advices of Iñigo after our mails exchange (as you probably saw), I modified the setup.py file to improve the installation method. I deleted the install.py file, everything is now done in setup.py.
To build the program you now just need to type,

`python setup.py build`

To build with debugging info,

`python setup.py build -g`

This commands will compile the code if necessary, and build the library.

To install the program,

`python setup.py install`

This will build the program (if necessary) and install it in the python library path.

There is only now the issue of the if condition in the cmakefile that you find obsolete, I will look for a better way.

marc

**Comment by mbarbry** [comment]
Hello Peter,

I saw Natalia this morning, so I guess you are back from holidays.

I have been working a bit on the code during this last month, and speed-up quite a bit some part of the code. I did not merge yet the code because I wanted to wait for you to review it. The main improvements are,

- full numba implementation for the hartree kernel => 86 times faster compare to original python version.
- using scipy blas routine instead of numpy dot in apply_rf0 brings a factor of 2.5

There is quite a few other parts of the code that are bottle neck and we should talk about them. Can we meet today?

You can find some profiling before improvements [here](http://158.227.181.130/plotly/pyscf/benchmark/Ags147-28-08-2017-tddft_iter_pyscf_no_numba_mkl.html) and after improvements [here](http://158.227.181.130/plotly/pyscf/benchmark/Ags147-28-08-2017-tddft_iter_pyscf_numba_mkl_blas.html). This tests are done for an Ags147 cluster (55 silver atoms + ghosts) on my computer, the original fortran code need 533 s.

Welcome back in Donostia,
marc

**Pull request merged**
