### PR TITLE
Gpaw hamiltonian

### PR DESCRIPTION
**Pull request by mbarbry**
Hello Peter,

So tddft_iter is now working with gpaw input, but I miss only one paraameter, telec.
From what I see it is the temperature of the system, is it correct? What is the unit? au?

marc

### CODE REVIEW

**Comment by kovalp** [comment]
Yes, it is temperature for the Fermi-Dirac distribution. Must be in
Hartree, yes. Just assume some small value by default. In gpaw there is
possible to do the occupations=FermiDirac(T) at the initialization of the
gpaw calculator. But I do not know what trace it leaves in the gpaw class.

Peter

**Comment by mbarbry** [comment]
ok, I used for the moment 1e-3, is it fine?

**Comment by kovalp** [comment]
0.0000317 Ha = 10 K

http://www.colby.edu/chemistry/PChem/Hartree.html

would be more sensible (close to zero).

**Comment by mbarbry** [comment]
ok, I see I was trying to use a value close to the siesta one (0.0019 Ha), I will use much smaller value.

**Comment by kovalp** [comment]
I pushed just now the unittes's corrections.

Peter

**Pull request merged**
